# Eigenvalue Problems

## Power Iteration

In [1]:
import numpy as np
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
import matplotlib.pyplot as plt
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets
from IPython.display import clear_output, display, Math

In [2]:
def Power_Iter(A, x0, iters):
    x = np.copy(x0)
    print ('Spectral Radius:')
    for i in range(iters):
        u = x/np.linalg.norm(x,2)
        x = np.dot(A, u)
        lam = np.dot(u,x)
        #if (i < iters-1):
        print ('iter %2d, %12.8f' % (i+1, lam))
    u = x/np.linalg.norm(x,2)
    print (u)
    #return lam, u

**Example** For
$$
  A = \left[\begin{array}{ccc} 1& 1 & 0.5 \\ 1 & 1 & 0.25 \\ 0.5 & 0.25 & 2\end{array}\right]
$$
computing $\rho(A)$ by Power Iteration.

In [3]:
A = np.array([[1, 1, 0.5],[1,1,0.25],[0.5,0.25,2]])
x0 = np.array([1,1,1])
print ("The build in answer: ")
np.linalg.eig(A)

The build in answer: 


(array([-0.01664728,  2.53652586,  1.48012142]),
 array([[ 0.72120713, -0.53148341, -0.44428106],
        [-0.68634929, -0.46147335, -0.56210942],
        [-0.09372796, -0.71032931,  0.69760113]]))

In [4]:
w = interactive(Power_Iter, A=fixed(A), x0=fixed(x0), iters=widgets.IntSlider(min=0,max=20,value=0))
display(w)

interactive(children=(IntSlider(value=0, description='iters', max=20), Output()), _dom_classes=('widget-intera…

## Inverse Power Iteration

In [11]:
def Inverse_Power(A, x0, s, iters):
    x = np.copy(x0)
    print ('The eigenvalue:')
    for i in range(iters):
        u = x/np.linalg.norm(x,2)
        x = np.linalg.solve(A-s*np.eye(np.size(x0)), u)
        lam = np.dot(u,x)
        if (i < iters-1):
            print ('iter %2d, %12.8f' % (i+1, 1/lam + s))
    u = x/np.linalg.norm(x,2)
    print (u)
    #return 1/lam+s, u

**Example** For
$$
  A = \left[\begin{array}{ccc} 2& 1 & 0 \\ 1 & 3 & 1 \\ 0 & 1 & 4\end{array}\right]
$$
Finding the eigenvalue of $A$ nearest to the real number $1.2679$ (the exact eigenvalue is $\lambda_3 = 3 - \sqrt{3}$), and the associated eigenvector.

In [13]:
A = np.array([[2, 1, 0],[1,3,1],[0,1,4]])
x0 = np.array([1,1,1])
np.linalg.eig(A)

(array([1.26794919, 3.        , 4.73205081]),
 array([[-0.78867513, -0.57735027,  0.21132487],
        [ 0.57735027, -0.57735027,  0.57735027],
        [-0.21132487,  0.57735027,  0.78867513]]))

In [14]:
w = interactive(Power_Iter, A=fixed(A), x0=fixed(x0), iters=widgets.IntSlider(min=0,max=40,value=0))
display(w)

interactive(children=(IntSlider(value=0, description='iters', max=40), Output()), _dom_classes=('widget-interact',))

In [15]:
s = 1.25
w = interactive(Inverse_Power, A=fixed(A), x0=fixed(x0), s=fixed(s), iters=widgets.IntSlider(min=0,max=20,value=0))
display(w)

interactive(children=(IntSlider(value=0, description='iters', max=20), Output()), _dom_classes=('widget-interact',))

In [16]:
def Rayleigh_Iter(A, x0, iters):
    x = np.copy(x0)
    print ('The eigenvalue:')
    for i in range(iters):
        u = x/np.linalg.norm(x,2)
        lam = np.dot(u,np.dot(A,u))
        x = np.linalg.solve(A-lam*np.eye(np.size(x0)), u)
        if (i < iters-1):
            print ('iter %2d, %12.8f' % (i+1, lam))
    u = x/np.linalg.norm(x,2)
    print (u)

In [17]:
w = interactive(Power_Iter, A=fixed(A), x0=fixed(x0), iters=widgets.IntSlider(min=0,max=40,value=0))
display(w)

interactive(children=(IntSlider(value=0, description='iters', max=40), Output()), _dom_classes=('widget-interact',))

In [18]:
w = interactive(Rayleigh_Iter, A=fixed(A), x0=fixed(x0), iters=widgets.IntSlider(min=0,max=20,value=0))
display(w)

interactive(children=(IntSlider(value=0, description='iters', max=20), Output()), _dom_classes=('widget-interact',))