In [1]:
import numpy as np
from scipy.linalg import lu

In [2]:
A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])

In [3]:
lu(A)

(array([[0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 0., 1., 0.]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.28571429,  1.        ,  0.        ,  0.        ],
        [ 0.71428571,  0.12      ,  1.        ,  0.        ],
        [ 0.71428571, -0.44      , -0.46153846,  1.        ]]),
 array([[ 7.        ,  5.        ,  6.        ,  6.        ],
        [ 0.        ,  3.57142857,  6.28571429,  5.28571429],
        [ 0.        ,  0.        , -1.04      ,  3.08      ],
        [ 0.        ,  0.        ,  0.        ,  7.46153846]]))

In [4]:
P, L, U = lu(A)

In [5]:
np.linalg.inv(P)

array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.]])

In [6]:
P = np.array([[0, 1, 0], [0, 0, 1], [1, 0, 0]])

In [7]:
print(P)
np.linalg.inv(P)

[[0 1 0]
 [0 0 1]
 [1 0 0]]


array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [8]:
np.dot(P,P)

array([[0, 0, 1],
       [1, 0, 0],
       [0, 1, 0]])

**Example**
\begin{align*}
    0.0003 x_1  + 1.566 x_2 & = 1.569 \\
    0.3454 x_1  - 2.436 x_2 & = 1.018
\end{align*}

In [9]:
A = np.array([[0.0003, 1.566, 1.569], [0.3454, -2.436, 1.018]])
(1.569 - 1.566*1.001)/0.0003

4.780000000000525

In [10]:
A = np.array([[0.0003, 1.566], [0.3454, -2.436]])
b = np.array([1.569, 1.018])
np.linalg.solve(A,b)

array([10.,  1.])