# The Direct Method for Solving Linear Systems

In [1]:
import numpy as np
from scipy.linalg import lu

## Gaussian Elimination

The simplest version of Gaussian Elimination only involves two operations as follows:
* Add or substrct a muliple of one equation from another.
* Multiply an equation by a nonzero constant.

### Solving a linear system by Gaussian elimination
The general form of a linear system for $n$ equations in $n$ unknown can be wriiten as 

To solve this linear system by Gaussian elimination 
1. Using the allowed row operations to eliminate the system to an upper triangular system

2. Using the back substituion (backsolving) to solve the upper triangular system

**Example**

Using Gaussian elimination to solve the following linear system
\begin{align}
 10^{-20}x_1 + x_2 & = 1 \\
 x_1 + 2x_2 & = 4
\end{align}
The argumented matrix reads
\begin{pmatrix}
10^{-20} & 1 & 1 \\
1 & 2 & 4
\end{pmatrix}

1. Elimination: $\text{Row}_2 = \text{Row}_2 - 10^{20}\times\text{Row}_1$ 

In [34]:
A = np.array([[1e-20, 1, 1], [1, 2, 4]])
A[1] = A[1] - 10**20*A[0]
print (A[1])

[ 0.e+00 -1.e+20 -1.e+20]


2. The echelon form of the argumented matrix reads
\begin{pmatrix}
10^{-20} & 1 & 1 \\
0 & -10^{20} & -10^{20}
\end{pmatrix}
3. Using the back substituion, the solution is 
$$ x_2 = 1,\qquad x_1 = 0.$$

**Example** (Hilbert Matrix)

The $n\times n$ Hilbert Matrix $H_n$ is defined as follows:
$$
H_n = \begin{pmatrix}{1} & {1 / 2} & {1 / 3} & {\cdots} & {1 / n} \\ {1 / 2} & {1 / 3} & {1 / 4} & {\cdots} & {1 /(n+1)} \\ {1 / 3} & {1 / 4} & {1 / 5} & {\cdots} & {1 /(n+2)} \\ {\cdots} & {\cdots} & {\cdots} & {\cdots} & {\cdots} \\ {1 / n} & {1 /(n+1)} & {1 /(n+2)} & {\cdots} & {1 /(2 n-1)}\end{pmatrix}
$$

Solving the linear system  
$$ H_n x = b$$
with 
$$ b = H_n \cdot\begin{pmatrix}1 \\ 1 \\ \vdots \\ 1\end{pmatrix} $$
for $n = 5, 10, 20$
* The exact solution is $x = \begin{pmatrix}1 \\ 1 \\ \vdots \\ 1\end{pmatrix} $

In [31]:
def hil(n):
    A = np.empty([n, n])
    for i in range(n):
        for j in range(n):
            A[i,j] = 1/(i+j+1)
    return A

def hil_example(n):
    A = hil(n)
    x_exact = np.zeros(n) + 1.
    b = np.dot(A, x_exact)
    x = np.linalg.solve(A, b)
    
    print ("The Hilbert Example")
    print ("Exact Solution: ", x_exact)
    print ("Numerical Solution: ", x)
    print ("Max Norm Error: ", np.max(x_exact - x))

In [33]:
n = 20
#A = hil(n)
#print (A, '\n')

hil_example(n)

The Hilbert Example
Exact Solution:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Numerical Solution:  [  0.99999973   1.00004237   0.99835796   1.02792418   0.73952115
   2.49989561  -4.7311483   16.23893703 -28.01643331  40.83944684
 -38.14836844  31.73258932 -33.33827867  55.58369907 -52.73705463
   4.75778788  52.47961466 -55.3242817   27.11720184  -3.7194526 ]
Max Norm Error:  56.32428169603723


In [3]:
lu(A)

(array([[0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 0., 1., 0.]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.28571429,  1.        ,  0.        ,  0.        ],
        [ 0.71428571,  0.12      ,  1.        ,  0.        ],
        [ 0.71428571, -0.44      , -0.46153846,  1.        ]]),
 array([[ 7.        ,  5.        ,  6.        ,  6.        ],
        [ 0.        ,  3.57142857,  6.28571429,  5.28571429],
        [ 0.        ,  0.        , -1.04      ,  3.08      ],
        [ 0.        ,  0.        ,  0.        ,  7.46153846]]))

In [4]:
P, L, U = lu(A)

In [5]:
np.linalg.inv(P)

array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.]])

In [6]:
P = np.array([[0, 1, 0], [0, 0, 1], [1, 0, 0]])

In [7]:
print(P)
np.linalg.inv(P)

[[0 1 0]
 [0 0 1]
 [1 0 0]]


array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [8]:
np.dot(P,P)

array([[0, 0, 1],
       [1, 0, 0],
       [0, 1, 0]])

**Example**
\begin{align*}
    0.0003 x_1  + 1.566 x_2 & = 1.569 \\
    0.3454 x_1  - 2.436 x_2 & = 1.018
\end{align*}

In [9]:
A = np.array([[0.0003, 1.566, 1.569], [0.3454, -2.436, 1.018]])
(1.569 - 1.566*1.001)/0.0003

4.780000000000525

In [10]:
A = np.array([[0.0003, 1.566], [0.3454, -2.436]])
b = np.array([1.569, 1.018])
np.linalg.solve(A,b)

array([10.,  1.])

In [13]:
A = np.array([[1e-20, 1, 1], [1, 2, 4]])
A[1] = A[1] - 1e20*A[0]
A[1]

array([ 0.e+00, -1.e+20, -1.e+20])

In [15]:
A = np.array([[1e-20, 1],[1, 2]])
b = np.array([1, 4])
np.linalg.solve(A,b)

array([2., 1.])

In [16]:
lu(A)

(array([[0., 1.],
        [1., 0.]]), array([[1.e+00, 0.e+00],
        [1.e-20, 1.e+00]]), array([[1., 2.],
        [0., 1.]]))